// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CPGClient.proto

#ifndef PROTOBUF_INCLUDED_CPGClient_2eproto
#define PROTOBUF_INCLUDED_CPGClient_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3006001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_CPGClient_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_CPGClient_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_CPGClient_2eproto();
namespace CPGClient {
class ConnectRQ;
class ConnectRQDefaultTypeInternal;
extern ConnectRQDefaultTypeInternal _ConnectRQ_default_instance_;
class ConnectRS;
class ConnectRSDefaultTypeInternal;
extern ConnectRSDefaultTypeInternal _ConnectRS_default_instance_;
class LoginRQ;
class LoginRQDefaultTypeInternal;
extern LoginRQDefaultTypeInternal _LoginRQ_default_instance_;
class LoginRS;
class LoginRSDefaultTypeInternal;
extern LoginRSDefaultTypeInternal _LoginRS_default_instance_;
}  // namespace CPGClient
namespace google {
namespace protobuf {
template<> ::CPGClient::ConnectRQ* Arena::CreateMaybeMessage<::CPGClient::ConnectRQ>(Arena*);
template<> ::CPGClient::ConnectRS* Arena::CreateMaybeMessage<::CPGClient::ConnectRS>(Arena*);
template<> ::CPGClient::LoginRQ* Arena::CreateMaybeMessage<::CPGClient::LoginRQ>(Arena*);
template<> ::CPGClient::LoginRS* Arena::CreateMaybeMessage<::CPGClient::LoginRS>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace CPGClient {

// ===================================================================

class ConnectRQ : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CPGClient.ConnectRQ) */ {
 public:
  ConnectRQ();
  virtual ~ConnectRQ();

  ConnectRQ(const ConnectRQ& from);

  inline ConnectRQ& operator=(const ConnectRQ& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ConnectRQ(ConnectRQ&& from) noexcept
    : ConnectRQ() {
    *this = ::std::move(from);
  }

  inline ConnectRQ& operator=(ConnectRQ&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ConnectRQ& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ConnectRQ* internal_default_instance() {
    return reinterpret_cast<const ConnectRQ*>(
               &_ConnectRQ_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ConnectRQ* other);
  friend void swap(ConnectRQ& a, ConnectRQ& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ConnectRQ* New() const final {
    return CreateMaybeMessage<ConnectRQ>(NULL);
  }

  ConnectRQ* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ConnectRQ>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ConnectRQ& from);
  void MergeFrom(const ConnectRQ& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConnectRQ* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 logicID = 1;
  void clear_logicid();
  static const int kLogicIDFieldNumber = 1;
  ::google::protobuf::int32 logicid() const;
  void set_logicid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CPGClient.ConnectRQ)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 logicid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_CPGClient_2eproto;
};
// -------------------------------------------------------------------

class ConnectRS : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CPGClient.ConnectRS) */ {
 public:
  ConnectRS();
  virtual ~ConnectRS();

  ConnectRS(const ConnectRS& from);

  inline ConnectRS& operator=(const ConnectRS& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ConnectRS(ConnectRS&& from) noexcept
    : ConnectRS() {
    *this = ::std::move(from);
  }

  inline ConnectRS& operator=(ConnectRS&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ConnectRS& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ConnectRS* internal_default_instance() {
    return reinterpret_cast<const ConnectRS*>(
               &_ConnectRS_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ConnectRS* other);
  friend void swap(ConnectRS& a, ConnectRS& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ConnectRS* New() const final {
    return CreateMaybeMessage<ConnectRS>(NULL);
  }

  ConnectRS* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ConnectRS>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ConnectRS& from);
  void MergeFrom(const ConnectRS& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConnectRS* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string ip = 3;
  void clear_ip();
  static const int kIpFieldNumber = 3;
  const ::std::string& ip() const;
  void set_ip(const ::std::string& value);
  #if LANG_CXX11
  void set_ip(::std::string&& value);
  #endif
  void set_ip(const char* value);
  void set_ip(const char* value, size_t size);
  ::std::string* mutable_ip();
  ::std::string* release_ip();
  void set_allocated_ip(::std::string* ip);

  // int32 result = 1;
  void clear_result();
  static const int kResultFieldNumber = 1;
  ::google::protobuf::int32 result() const;
  void set_result(::google::protobuf::int32 value);

  // int32 port = 2;
  void clear_port();
  static const int kPortFieldNumber = 2;
  ::google::protobuf::int32 port() const;
  void set_port(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CPGClient.ConnectRS)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr ip_;
  ::google::protobuf::int32 result_;
  ::google::protobuf::int32 port_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_CPGClient_2eproto;
};
// -------------------------------------------------------------------

class LoginRQ : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CPGClient.LoginRQ) */ {
 public:
  LoginRQ();
  virtual ~LoginRQ();

  LoginRQ(const LoginRQ& from);

  inline LoginRQ& operator=(const LoginRQ& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LoginRQ(LoginRQ&& from) noexcept
    : LoginRQ() {
    *this = ::std::move(from);
  }

  inline LoginRQ& operator=(LoginRQ&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const LoginRQ& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LoginRQ* internal_default_instance() {
    return reinterpret_cast<const LoginRQ*>(
               &_LoginRQ_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(LoginRQ* other);
  friend void swap(LoginRQ& a, LoginRQ& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LoginRQ* New() const final {
    return CreateMaybeMessage<LoginRQ>(NULL);
  }

  LoginRQ* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LoginRQ>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LoginRQ& from);
  void MergeFrom(const LoginRQ& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoginRQ* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string token = 2;
  void clear_token();
  static const int kTokenFieldNumber = 2;
  const ::std::string& token() const;
  void set_token(const ::std::string& value);
  #if LANG_CXX11
  void set_token(::std::string&& value);
  #endif
  void set_token(const char* value);
  void set_token(const char* value, size_t size);
  ::std::string* mutable_token();
  ::std::string* release_token();
  void set_allocated_token(::std::string* token);

  // int32 uid = 1;
  void clear_uid();
  static const int kUidFieldNumber = 1;
  ::google::protobuf::int32 uid() const;
  void set_uid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CPGClient.LoginRQ)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr token_;
  ::google::protobuf::int32 uid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_CPGClient_2eproto;
};
// -------------------------------------------------------------------

class LoginRS : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CPGClient.LoginRS) */ {
 public:
  LoginRS();
  virtual ~LoginRS();

  LoginRS(const LoginRS& from);

  inline LoginRS& operator=(const LoginRS& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LoginRS(LoginRS&& from) noexcept
    : LoginRS() {
    *this = ::std::move(from);
  }

  inline LoginRS& operator=(LoginRS&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const LoginRS& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LoginRS* internal_default_instance() {
    return reinterpret_cast<const LoginRS*>(
               &_LoginRS_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(LoginRS* other);
  friend void swap(LoginRS& a, LoginRS& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LoginRS* New() const final {
    return CreateMaybeMessage<LoginRS>(NULL);
  }

  LoginRS* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LoginRS>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LoginRS& from);
  void MergeFrom(const LoginRS& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoginRS* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 result = 1;
  void clear_result();
  static const int kResultFieldNumber = 1;
  ::google::protobuf::int32 result() const;
  void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CPGClient.LoginRS)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 result_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_CPGClient_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ConnectRQ

// int32 logicID = 1;
inline void ConnectRQ::clear_logicid() {
  logicid_ = 0;
}
inline ::google::protobuf::int32 ConnectRQ::logicid() const {
  // @@protoc_insertion_point(field_get:CPGClient.ConnectRQ.logicID)
  return logicid_;
}
inline void ConnectRQ::set_logicid(::google::protobuf::int32 value) {
  
  logicid_ = value;
  // @@protoc_insertion_point(field_set:CPGClient.ConnectRQ.logicID)
}

// -------------------------------------------------------------------

// ConnectRS

// int32 result = 1;
inline void ConnectRS::clear_result() {
  result_ = 0;
}
inline ::google::protobuf::int32 ConnectRS::result() const {
  // @@protoc_insertion_point(field_get:CPGClient.ConnectRS.result)
  return result_;
}
inline void ConnectRS::set_result(::google::protobuf::int32 value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:CPGClient.ConnectRS.result)
}

// int32 port = 2;
inline void ConnectRS::clear_port() {
  port_ = 0;
}
inline ::google::protobuf::int32 ConnectRS::port() const {
  // @@protoc_insertion_point(field_get:CPGClient.ConnectRS.port)
  return port_;
}
inline void ConnectRS::set_port(::google::protobuf::int32 value) {
  
  port_ = value;
  // @@protoc_insertion_point(field_set:CPGClient.ConnectRS.port)
}

// string ip = 3;
inline void ConnectRS::clear_ip() {
  ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ConnectRS::ip() const {
  // @@protoc_insertion_point(field_get:CPGClient.ConnectRS.ip)
  return ip_.GetNoArena();
}
inline void ConnectRS::set_ip(const ::std::string& value) {
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CPGClient.ConnectRS.ip)
}
#if LANG_CXX11
inline void ConnectRS::set_ip(::std::string&& value) {
  
  ip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CPGClient.ConnectRS.ip)
}
#endif
inline void ConnectRS::set_ip(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CPGClient.ConnectRS.ip)
}
inline void ConnectRS::set_ip(const char* value, size_t size) {
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CPGClient.ConnectRS.ip)
}
inline ::std::string* ConnectRS::mutable_ip() {
  
  // @@protoc_insertion_point(field_mutable:CPGClient.ConnectRS.ip)
  return ip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ConnectRS::release_ip() {
  // @@protoc_insertion_point(field_release:CPGClient.ConnectRS.ip)
  
  return ip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ConnectRS::set_allocated_ip(::std::string* ip) {
  if (ip != NULL) {
    
  } else {
    
  }
  ip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ip);
  // @@protoc_insertion_point(field_set_allocated:CPGClient.ConnectRS.ip)
}

// -------------------------------------------------------------------

// LoginRQ

// int32 uid = 1;
inline void LoginRQ::clear_uid() {
  uid_ = 0;
}
inline ::google::protobuf::int32 LoginRQ::uid() const {
  // @@protoc_insertion_point(field_get:CPGClient.LoginRQ.uid)
  return uid_;
}
inline void LoginRQ::set_uid(::google::protobuf::int32 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:CPGClient.LoginRQ.uid)
}

// string token = 2;
inline void LoginRQ::clear_token() {
  token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LoginRQ::token() const {
  // @@protoc_insertion_point(field_get:CPGClient.LoginRQ.token)
  return token_.GetNoArena();
}
inline void LoginRQ::set_token(const ::std::string& value) {
  
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CPGClient.LoginRQ.token)
}
#if LANG_CXX11
inline void LoginRQ::set_token(::std::string&& value) {
  
  token_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CPGClient.LoginRQ.token)
}
#endif
inline void LoginRQ::set_token(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CPGClient.LoginRQ.token)
}
inline void LoginRQ::set_token(const char* value, size_t size) {
  
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CPGClient.LoginRQ.token)
}
inline ::std::string* LoginRQ::mutable_token() {
  
  // @@protoc_insertion_point(field_mutable:CPGClient.LoginRQ.token)
  return token_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LoginRQ::release_token() {
  // @@protoc_insertion_point(field_release:CPGClient.LoginRQ.token)
  
  return token_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginRQ::set_allocated_token(::std::string* token) {
  if (token != NULL) {
    
  } else {
    
  }
  token_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), token);
  // @@protoc_insertion_point(field_set_allocated:CPGClient.LoginRQ.token)
}

// -------------------------------------------------------------------

// LoginRS

// int32 result = 1;
inline void LoginRS::clear_result() {
  result_ = 0;
}
inline ::google::protobuf::int32 LoginRS::result() const {
  // @@protoc_insertion_point(field_get:CPGClient.LoginRS.result)
  return result_;
}
inline void LoginRS::set_result(::google::protobuf::int32 value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:CPGClient.LoginRS.result)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace CPGClient

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_CPGClient_2eproto
